"""добавлен статус

Revision ID: 196bf693a6f5
Revises: 8692691ea3cb
Create Date: 2026-04-20 16:24:32.285682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196bf693a6f5'
down_revision: Union[str, Sequence[str], None] = '8692691ea3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'status')
    # ### end Alembic commands ###
