"""add settings and defaults

Revision ID: 68900a16ad81
Revises: b2c3d4e5f6a7
Create Date: 2026-05-19 16:57:08.856199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68900a16ad81'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_live_count'), table_name='assignments')
    op.add_column('datasets', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'settings')
    op.create_index(op.f('ix_assignments_live_count'), 'assignments', ['task_id', 'status', 'expires_at'], unique=False)
    # ### end Alembic commands ###
